apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        command: ["/go/bin/dlv"]
        args: ["--listen=:2345", "--headless=true", "--api-version=2", "exec", "/go/src/github.com/kubeflow/kubeflow/components/profile-controller/manager"]
        env:
        - name: project
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: project
        image: gcr.io/$(project)/profile-controller:latest
        ports:
        - containerPort: 2345
        securityContext:
          privileged: true
