apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/instance: katib-controller-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: katib-controller
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
- overlays/istio/katib-ui-virtual-service.yaml
