apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- vpc.yaml
configMapGenerator:
- name: alb-ingress-controller-vpc-parameters
  env: params.env
vars:
- name: VPC_ID
  objref:
    kind: ConfigMap
    name: alb-ingress-controller-vpc-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.vpcId
- name: REGION
  objref:
    kind: ConfigMap
    name: alb-ingress-controller-vpc-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.region
