apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo
      app.kubernetes.io/instance: argo-v2.3.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: argo
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v2.3.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: core
    kind: Service
  - group: networking.istio.io
    kind: VirtualService
  descriptor:
    type: argo
    version: v1beta1
    description: Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes
    maintainers: []
    owners: []
    keywords:
     - argo
     - kubeflow
    links:
    - description: About
      url: https://github.com/argoproj/argo
  addOwnerRef: true

