apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
#  namespace: deployment
  generation: 1
  labels:
    app: seldon
  name: mean-classifier
spec:
  annotations:
    seldon.io/engine-log-message-type: seldon.message.pair
    seldon.io/engine-log-messages-externally: "false"
    seldon.io/engine-log-requests: "false"
    seldon.io/engine-log-responses: "false"
    seldon.io/headless-svc: "false"
  name: mean-classifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: INFO
          - name: PREDICTIVE_UNIT_SERVICE_PORT
            value: "9000"
          - name: PREDICTIVE_UNIT_ID
            value: classifier
          - name: PREDICTOR_ID
            value: mean-classifier
          - name: SELDON_DEPLOYMENT_ID
            value: mean-classifier
          image: pipelineai/predict-meanclassifier:2.0.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 10
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          name: classifier
          ports:
          - containerPort: 9000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          resources:
            requests:
              memory: 1Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 20
        volumes:
        - downwardAPI:
            defaultMode: 420
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations
              path: annotations
          name: podinfo
    graph:
      children: []
      endpoint:
        service_host: localhost
        service_port: 9000
        type: REST
      implementation: UNKNOWN_IMPLEMENTATION
      name: classifier
      type: MODEL
    labels:
      fluentd: "true"
      version: v1
    name: mean-classifier
    replicas: 1
    svcOrchSpec:
      env: []
      resources:
        requests:
          cpu: "0.1"
