apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
- name: parameters
  behavior: merge
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
