apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pipelines-viewer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipelines-viewer
      app.kubernetes.io/instance: pipelines-viewer-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: pipelines-viewer
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: pipelines-viewer
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
     - pipelines-viewer
     - kubeflow
    links:
    - description: About
      url: ""
  addOwnerRef: true
