apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: pipelines-viewer
  app.kubernetes.io/instance: pipelines-viewer-0.1.31
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: pipelines-viewer
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.1.31
