from setuptools import setup

setup(
    packages=['candidate_data_processors/'],
    name='candidate_data_processors',
    version='1.0.0',
    description='This module is auto-generated by SageMaker AutoML. '
                'It contains candidate data processing code and the '
                'scaffolding to run them in SageMaker.',
    author='Amazon Web Services',
    license='Apache License 2.0',
    include_package_data=True,
)
