apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: argo
  app.kubernetes.io/instance: argo-v2.3.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: argo
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v2.3.0
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/istio/virtual-service.yaml
- overlays/application/application.yaml
