apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: mpijob
  app.kubernetes.io/instance: mpi-operator
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: mpi-operator
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
