apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pipeline-visualization-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pipeline-visualization-service
      app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: pipeline-visualization-service
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: pipeline-visualization-service
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
     - pipeline-visualization-service
     - kubeflow
    links:
    - description: About
      url: ""
  addOwnerRef: true
