apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: notebook-controller
  app.kubernetes.io/instance: notebook-controller-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: notebook-controller
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
