apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: nvidia-device-plugin
  app.kubernetes.io/instance: nvidia-device-plugin-1.0.0-beta
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: nvidia-device-plugin
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0-beta
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
