apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mpi-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mpi-operator
      app.kubernetes.io/instance: mpi-operator
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: mpijob
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7
  componentKinds:
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: MPIJob
  descriptor:
    type: "mpi-operator"
    version: "v1alpha1"
    description: "Mpi-operator allows users to create and manage the \"MPIJob\" custom resource."
    keywords:
    - "mpijob"
    - "mpi-operator"
    links:
    - description: About
      url: "https://github.com/kubeflow/mpi-operator"
