apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: persistent-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: persistent-agent
      app.kubernetes.io/instance: persistent-agent-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: persistent-agent
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: persistent-agent
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
     - persistent-agent
     - kubeflow
    links:
    - description: About
      url: ""
  addOwnerRef: true
