apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: persistent-agent
  app.kubernetes.io/instance: persistent-agent-0.1.31
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: persistent-agent
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.1.31
