# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- seldon-config-cm.yaml
- seldon-manager-sa.yaml
- seldon-operator-controller-manager-service-svc.yaml
- seldon-operator-controller-manager-statefulset.yaml
- seldon-operator-manager-role-clusterrole.yaml
- seldon-operator-manager-rolebinding-crb.yaml
- seldon-operator-webhook-server-secret-secret.yaml
- seldondeployments.machinelearning.seldon.io-crd.yaml
- webhook-server-service-svc.yaml
images:
- name: docker.io/seldonio/seldon-core-operator
  newName: docker.io/seldonio/seldon-core-operator
  newTag: 0.4.1
