apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: seldon-core-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: seldon-core-operator
    helm.sh/chart: seldon-core-operator-0.4.1
  name: seldon-manager
  namespace: kubeflow
