apiVersion: v1
data:
  credentials: |-
    {
       "gcs" : {
           "gcsCredentialFileName": "gcloud-application-credentials.json"
       },
       "s3" : {
           "s3AccessKeyIDName": "awsAccessKeyID",
           "s3SecretAccessKeyName": "awsSecretAccessKey"
       }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: seldon-core-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: seldon-core-operator
    helm.sh/chart: seldon-core-operator-0.4.1
  name: seldon-config
  namespace: kubeflow
