apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: seldon-core-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: seldon-core-operator
    helm.sh/chart: seldon-core-operator-0.4.1
  name: seldon-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-operator-manager-role
subjects:
- kind: ServiceAccount
  name: seldon-manager
  namespace: kubeflow
