apiVersion: v1
kind: PersistentVolume
metadata:
  name: $(minioPvName)
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: $(minioPd)
    fsType: ext4
