apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: spartakus
  app.kubernetes.io/instance: spartakus-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: spartakus
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
